# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(QtWidgets.QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(896, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(310, 180, 561, 371))
        self.widget.setObjectName("widget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 170, 301, 381))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_3.setGeometry(QtCore.QRect(240, 40, 51, 341))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.a_5_m_Edit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.a_5_m_Edit.setObjectName("a_5_m_Edit")
        self.verticalLayout_5.addWidget(self.a_5_m_Edit)
        self.a_4_m_Edit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.a_4_m_Edit.setObjectName("a_4_m_Edit")
        self.verticalLayout_5.addWidget(self.a_4_m_Edit)
        self.a_3_m_Edit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.a_3_m_Edit.setObjectName("a_3_m_Edit")
        self.verticalLayout_5.addWidget(self.a_3_m_Edit)
        self.a_2_m_Edit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.a_2_m_Edit.setObjectName("a_2_m_Edit")
        self.verticalLayout_5.addWidget(self.a_2_m_Edit)
        self.a_1_m_Edit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.a_1_m_Edit.setObjectName("a_1_m_Edit")
        self.verticalLayout_5.addWidget(self.a_1_m_Edit)
        self.b_1_m_Edit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.b_1_m_Edit.setObjectName("b_1_m_Edit")
        self.verticalLayout_5.addWidget(self.b_1_m_Edit)
        self.b_2_m_Edit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.b_2_m_Edit.setObjectName("b_2_m_Edit")
        self.verticalLayout_5.addWidget(self.b_2_m_Edit)
        self.b_3_m_Edit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.b_3_m_Edit.setObjectName("b_3_m_Edit")
        self.verticalLayout_5.addWidget(self.b_3_m_Edit)
        self.b_4_m_Edit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.b_4_m_Edit.setObjectName("b_4_m_Edit")
        self.verticalLayout_5.addWidget(self.b_4_m_Edit)
        self.b_5_m_Edit = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.b_5_m_Edit.setObjectName("b_5_m_Edit")
        self.verticalLayout_5.addWidget(self.b_5_m_Edit)
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(190, 40, 51, 341))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.a_5_p_Edit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.a_5_p_Edit.setObjectName("a_5_p_Edit")
        self.verticalLayout_4.addWidget(self.a_5_p_Edit)
        self.a_4_p_Edit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.a_4_p_Edit.setObjectName("a_4_p_Edit")
        self.verticalLayout_4.addWidget(self.a_4_p_Edit)
        self.a_3_p_Edit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.a_3_p_Edit.setObjectName("a_3_p_Edit")
        self.verticalLayout_4.addWidget(self.a_3_p_Edit)
        self.a_2_p_Edit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.a_2_p_Edit.setObjectName("a_2_p_Edit")
        self.verticalLayout_4.addWidget(self.a_2_p_Edit)
        self.a_1_p_Edit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.a_1_p_Edit.setObjectName("a_1_p_Edit")
        self.verticalLayout_4.addWidget(self.a_1_p_Edit)
        self.b_1_p_Edit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.b_1_p_Edit.setObjectName("b_1_p_Edit")
        self.verticalLayout_4.addWidget(self.b_1_p_Edit)
        self.b_2_p_Edit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.b_2_p_Edit.setObjectName("b_2_p_Edit")
        self.verticalLayout_4.addWidget(self.b_2_p_Edit)
        self.b_3_p_Edit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.b_3_p_Edit.setObjectName("b_3_p_Edit")
        self.verticalLayout_4.addWidget(self.b_3_p_Edit)
        self.b_4_p_Edit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.b_4_p_Edit.setObjectName("b_4_p_Edit")
        self.verticalLayout_4.addWidget(self.b_4_p_Edit)
        self.b_5_p_Edit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.b_5_p_Edit.setObjectName("b_5_p_Edit")
        self.verticalLayout_4.addWidget(self.b_5_p_Edit)
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(160, 40, 31, 341))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_2.addWidget(self.label_18)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_2.addWidget(self.label_15)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(200, 20, 41, 16))
        self.label_10.setObjectName("label_10")
        self.label_26 = QtWidgets.QLabel(self.groupBox)
        self.label_26.setGeometry(QtCore.QRect(250, 20, 51, 16))
        self.label_26.setObjectName("label_26")
        self.Insert_Code = QtWidgets.QLineEdit(self.groupBox)
        self.Insert_Code.setGeometry(QtCore.QRect(10, 30, 71, 24))
        self.Insert_Code.setObjectName("Insert_Code")
        self.Search_Button = QtWidgets.QPushButton(self.groupBox)
        self.Search_Button.setGeometry(QtCore.QRect(90, 30, 51, 24))
        self.Search_Button.setObjectName("Search_Button")
        self.company_name = QtWidgets.QLabel(self.groupBox)
        self.company_name.setGeometry(QtCore.QRect(10, 60, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.company_name.setFont(font)
        self.company_name.setObjectName("company_name")
        self.widget1 = QtWidgets.QWidget(self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(11, 101, 59, 271))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Up_Prob_Label = QtWidgets.QLabel(self.widget1)
        self.Up_Prob_Label.setObjectName("Up_Prob_Label")
        self.verticalLayout.addWidget(self.Up_Prob_Label)
        self.label_6 = QtWidgets.QLabel(self.widget1)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_14 = QtWidgets.QLabel(self.widget1)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.amount_Edit = QtWidgets.QLineEdit(self.groupBox)
        self.amount_Edit.setGeometry(QtCore.QRect(71, 351, 81, 24))
        self.amount_Edit.setObjectName("amount_Edit")
        self.pre_clos_Edit = QtWidgets.QLineEdit(self.groupBox)
        self.pre_clos_Edit.setGeometry(QtCore.QRect(71, 176, 69, 24))
        self.pre_clos_Edit.setObjectName("pre_clos_Edit")
        self.price_now_Edit = QtWidgets.QLineEdit(self.groupBox)
        self.price_now_Edit.setGeometry(QtCore.QRect(71, 141, 69, 24))
        self.price_now_Edit.setObjectName("price_now_Edit")
        self.low_Edit = QtWidgets.QLineEdit(self.groupBox)
        self.low_Edit.setGeometry(QtCore.QRect(71, 281, 69, 24))
        self.low_Edit.setObjectName("low_Edit")
        self.open_Edit = QtWidgets.QLineEdit(self.groupBox)
        self.open_Edit.setGeometry(QtCore.QRect(71, 211, 69, 24))
        self.open_Edit.setObjectName("open_Edit")
        self.prob_up_Edit = QtWidgets.QLineEdit(self.groupBox)
        self.prob_up_Edit.setGeometry(QtCore.QRect(71, 106, 69, 24))
        self.prob_up_Edit.setObjectName("prob_up_Edit")
        self.volume_Edit = QtWidgets.QLineEdit(self.groupBox)
        self.volume_Edit.setGeometry(QtCore.QRect(71, 316, 81, 24))
        self.volume_Edit.setObjectName("volume_Edit")
        self.high_Edit = QtWidgets.QLineEdit(self.groupBox)
        self.high_Edit.setGeometry(QtCore.QRect(71, 246, 69, 24))
        self.high_Edit.setObjectName("high_Edit")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(120, 20, 81, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.get_top_eight = QtWidgets.QPushButton(self.centralwidget)
        self.get_top_eight.setGeometry(QtCore.QRect(10, 10, 101, 41))
        self.get_top_eight.setStyleSheet("color: rgb(255, 0, 0);")
        self.get_top_eight.setObjectName("get_top_eight")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 60, 281, 26))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.top_1 = QtWidgets.QPushButton(self.layoutWidget1)
        self.top_1.setObjectName("top_1")
        self.horizontalLayout.addWidget(self.top_1)
        self.top_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.top_2.setObjectName("top_2")
        self.horizontalLayout.addWidget(self.top_2)
        self.top_3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.top_3.setObjectName("top_3")
        self.horizontalLayout.addWidget(self.top_3)
        self.top_4 = QtWidgets.QPushButton(self.layoutWidget1)
        self.top_4.setObjectName("top_4")
        self.horizontalLayout.addWidget(self.top_4)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 120, 281, 26))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.top_5 = QtWidgets.QPushButton(self.layoutWidget2)
        self.top_5.setObjectName("top_5")
        self.horizontalLayout_2.addWidget(self.top_5)
        self.top_6 = QtWidgets.QPushButton(self.layoutWidget2)
        self.top_6.setObjectName("top_6")
        self.horizontalLayout_2.addWidget(self.top_6)
        self.top_7 = QtWidgets.QPushButton(self.layoutWidget2)
        self.top_7.setObjectName("top_7")
        self.horizontalLayout_2.addWidget(self.top_7)
        self.top_8 = QtWidgets.QPushButton(self.layoutWidget2)
        self.top_8.setObjectName("top_8")
        self.horizontalLayout_2.addWidget(self.top_8)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(11, 91, 281, 20))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Top1_label = QtWidgets.QLabel(self.layoutWidget3)
        self.Top1_label.setObjectName("Top1_label")
        self.horizontalLayout_3.addWidget(self.Top1_label)
        self.Top2_label = QtWidgets.QLabel(self.layoutWidget3)
        self.Top2_label.setObjectName("Top2_label")
        self.horizontalLayout_3.addWidget(self.Top2_label)
        self.Top3_label = QtWidgets.QLabel(self.layoutWidget3)
        self.Top3_label.setObjectName("Top3_label")
        self.horizontalLayout_3.addWidget(self.Top3_label)
        self.Top4_label = QtWidgets.QLabel(self.layoutWidget3)
        self.Top4_label.setObjectName("Top4_label")
        self.horizontalLayout_3.addWidget(self.Top4_label)
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(11, 150, 281, 20))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Top5_label = QtWidgets.QLabel(self.layoutWidget4)
        self.Top5_label.setObjectName("Top5_label")
        self.horizontalLayout_4.addWidget(self.Top5_label)
        self.Top6_label = QtWidgets.QLabel(self.layoutWidget4)
        self.Top6_label.setObjectName("Top6_label")
        self.horizontalLayout_4.addWidget(self.Top6_label)
        self.Top7_label = QtWidgets.QLabel(self.layoutWidget4)
        self.Top7_label.setObjectName("Top7_label")
        self.horizontalLayout_4.addWidget(self.Top7_label)
        self.Top8_label = QtWidgets.QLabel(self.layoutWidget4)
        self.Top8_label.setObjectName("Top8_label")
        self.horizontalLayout_4.addWidget(self.Top8_label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 896, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionGet_Top_Ten = QtWidgets.QAction(MainWindow)
        self.actionGet_Top_Ten.setObjectName("actionGet_Top_Ten")
        self.actionGet_Last_Ten = QtWidgets.QAction(MainWindow)
        self.actionGet_Last_Ten.setObjectName("actionGet_Last_Ten")
        self.menuMenu.addAction(self.actionGet_Top_Ten)
        self.menuMenu.addAction(self.actionGet_Last_Ten)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "ask5"))
        self.label_18.setText(_translate("MainWindow", "ask4"))
        self.label_8.setText(_translate("MainWindow", "ask3"))
        self.label_16.setText(_translate("MainWindow", "ask2"))
        self.label_9.setText(_translate("MainWindow", "ask1"))
        self.label_12.setText(_translate("MainWindow", "buy1"))
        self.label_17.setText(_translate("MainWindow", "buy2"))
        self.label_19.setText(_translate("MainWindow", "buy3"))
        self.label_13.setText(_translate("MainWindow", "buy4"))
        self.label_15.setText(_translate("MainWindow", "buy5"))
        self.label_10.setText(_translate("MainWindow", "price"))
        self.label_26.setText(_translate("MainWindow", "amount"))
        self.Insert_Code.setText(_translate("MainWindow", "000002"))
        self.Search_Button.setText(_translate("MainWindow", "Search"))
        self.company_name.setText(_translate("MainWindow", " Company"))
        self.Up_Prob_Label.setText(_translate("MainWindow", "Prob_Up"))
        self.label_6.setText(_translate("MainWindow", "Price_Now"))
        self.label_14.setText(_translate("MainWindow", "pre_close"))
        self.label.setText(_translate("MainWindow", "open"))
        self.label_3.setText(_translate("MainWindow", "high"))
        self.label_4.setText(_translate("MainWindow", "low"))
        self.label_5.setText(_translate("MainWindow", "volume"))
        self.label_2.setText(_translate("MainWindow", "anmunt"))
        self.get_top_eight.setText(_translate("MainWindow", "Get Top Eight"))
        self.top_1.setText(_translate("MainWindow", "--"))
        self.top_2.setText(_translate("MainWindow", "--"))
        self.top_3.setText(_translate("MainWindow", "--"))
        self.top_4.setText(_translate("MainWindow", "--"))
        self.top_5.setText(_translate("MainWindow", "--"))
        self.top_6.setText(_translate("MainWindow", "--"))
        self.top_7.setText(_translate("MainWindow", "--"))
        self.top_8.setText(_translate("MainWindow", "--"))
        self.Top1_label.setText(_translate("MainWindow", "        --"))
        self.Top2_label.setText(_translate("MainWindow", "        --"))
        self.Top3_label.setText(_translate("MainWindow", "        --"))
        self.Top4_label.setText(_translate("MainWindow", "        --"))
        self.Top5_label.setText(_translate("MainWindow", "        --"))
        self.Top6_label.setText(_translate("MainWindow", "        --"))
        self.Top7_label.setText(_translate("MainWindow", "        --"))
        self.Top8_label.setText(_translate("MainWindow", "        --"))
        self.menuMenu.setTitle(_translate("MainWindow", "Tool"))
        self.actionGet_Top_Ten.setText(_translate("MainWindow", "Get Top Ten"))
        self.actionGet_Last_Ten.setText(_translate("MainWindow", "Get Last Ten"))

